import Foundation
import AppKit

#if canImport(Sparkle)
import Sparkle

/// Wraps Sparkle's standard updater so the rest of the app stays agnostic.
/// Provides the feed URL programmatically (via `SPUUpdaterDelegate`) so no
/// Info.plist edits are required.
@MainActor
final class UpdateService: NSObject, SPUUpdaterDelegate {

    /// GitHub Releases pattern — Sparkle fetches this on every launch + on
    /// user-triggered checks. The URL always points at the latest published
    /// appcast.xml so we don't have to bake the version in the app.
    private let feedURLString = "https://github.com/misilab/misiqcpro/releases/latest/download/appcast.xml"

    /// Sparkle public Ed25519 key for verifying update signatures (base64).
    /// Generated by `scripts/generate_sparkle_keys.swift`. The matching private
    /// key lives in `scripts/output/sparkle_private_key.dat` (KEEP SECRET).
    static let publicEDKey = "+DhDxBBLEHOkWZeMH7rQPFJ10TX5ngongiGboO1Ualg="

    private(set) lazy var updaterController: SPUStandardUpdaterController = {
        SPUStandardUpdaterController(
            startingUpdater: true,
            updaterDelegate: self,
            userDriverDelegate: nil
        )
    }()

    func checkForUpdates() {
        updaterController.checkForUpdates(nil)
    }

    // MARK: - SPUUpdaterDelegate

    nonisolated func feedURLString(for updater: SPUUpdater) -> String? {
        feedURLString
    }
}

#else

/// Stub used while Sparkle hasn't been linked into the project yet.
/// Replaced by the real implementation as soon as the SPM package is added.
@MainActor
final class UpdateService {
    func checkForUpdates() {
        let alert = NSAlert()
        alert.messageText = "Sparkle non intégré"
        alert.informativeText =
            "Le module de mise à jour Sparkle n'est pas encore lié au projet.\n\n" +
            "Pour l'activer : Xcode → File → Add Packages… → " +
            "https://github.com/sparkle-project/Sparkle → Add Package.\n\n" +
            "Voir scripts/SETUP_SPARKLE.md pour les détails."
        alert.alertStyle = .informational
        alert.runModal()
    }
}

#endif
